apiVersion: apps/v1
kind: Deployment
metadata:
  name: progdisbueapplication
spec:
  replicas: 3
  selector:
    matchLabels:
      app: progdisbueapplication
  template:
    metadata:
      labels:
        app: progdisbueapplication
    spec:
      containers:
        - name: app
          image: ndawyaya/progdisbueapplication
          ports:
            - containerPort: 8080
          env:
            - name: MONGO_URL
              value: mongodb://mongo:27017/dev
          imagePullPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: progdisbueapplication
spec:
  selector:
    app: progdisbueapplication
  ports:
    - port: 80
      targetPort: 8080
  type: LoadBalancer
